// Shared high-frequency Italian vocabulary pool.
//
// One bank powers the games, pronunciation, and Smart Review. Words are chosen
// for everyday usefulness (the most common words cover most real conversation),
// grouped by theme. Each entry: Italian term, English meaning, optional emoji.
// `id` is the Italian word, so a child's mastery of a word is shared everywhere.

/// One vocabulary entry.
class VocabWord {
  const VocabWord(this.it, this.en, [this.emoji = '']);

  /// Italian word/phrase (also the stable id).
  final String it;

  /// English meaning.
  final String en;

  /// Optional emoji cue ('' when none fits).
  final String emoji;

  String get id => it;
  bool get hasEmoji => emoji.isNotEmpty;
}

abstract final class VocabBank {
  static const List<VocabWord> all = <VocabWord>[
    // --- Greetings & basics ---
    VocabWord('Ciao', 'Hi / Bye', '👋'),
    VocabWord('Salve', 'Hello'),
    VocabWord('Buongiorno', 'Good morning', '☀️'),
    VocabWord('Buonasera', 'Good evening', '🌆'),
    VocabWord('Buonanotte', 'Good night', '🌙'),
    VocabWord('Arrivederci', 'Goodbye', '👋'),
    VocabWord('Grazie', 'Thank you', '🙏'),
    VocabWord('Prego', "You're welcome"),
    VocabWord('Per favore', 'Please', '🙏'),
    VocabWord('Scusa', 'Excuse me'),
    VocabWord('Mi dispiace', "I'm sorry", '😔'),
    VocabWord('Sì', 'Yes', '✅'),
    VocabWord('No', 'No', '❌'),
    VocabWord('Forse', 'Maybe'),
    VocabWord('Va bene', 'Okay', '👍'),
    VocabWord('Bene', 'Well / Good', '😊'),
    VocabWord('Male', 'Badly'),
    VocabWord('Piacere', 'Nice to meet you', '🤝'),
    VocabWord('Benvenuto', 'Welcome'),

    // --- Numbers ---
    VocabWord('Zero', 'Zero'),
    VocabWord('Uno', 'One', '1️⃣'),
    VocabWord('Due', 'Two', '2️⃣'),
    VocabWord('Tre', 'Three', '3️⃣'),
    VocabWord('Quattro', 'Four', '4️⃣'),
    VocabWord('Cinque', 'Five', '5️⃣'),
    VocabWord('Sei', 'Six', '6️⃣'),
    VocabWord('Sette', 'Seven', '7️⃣'),
    VocabWord('Otto', 'Eight', '8️⃣'),
    VocabWord('Nove', 'Nine', '9️⃣'),
    VocabWord('Dieci', 'Ten', '🔟'),
    VocabWord('Undici', 'Eleven'),
    VocabWord('Dodici', 'Twelve'),
    VocabWord('Tredici', 'Thirteen'),
    VocabWord('Quattordici', 'Fourteen'),
    VocabWord('Quindici', 'Fifteen'),
    VocabWord('Sedici', 'Sixteen'),
    VocabWord('Diciassette', 'Seventeen'),
    VocabWord('Diciotto', 'Eighteen'),
    VocabWord('Diciannove', 'Nineteen'),
    VocabWord('Venti', 'Twenty'),
    VocabWord('Trenta', 'Thirty'),
    VocabWord('Quaranta', 'Forty'),
    VocabWord('Cinquanta', 'Fifty'),
    VocabWord('Sessanta', 'Sixty'),
    VocabWord('Settanta', 'Seventy'),
    VocabWord('Ottanta', 'Eighty'),
    VocabWord('Novanta', 'Ninety'),
    VocabWord('Cento', 'Hundred', '💯'),
    VocabWord('Mille', 'Thousand'),

    // --- Colors ---
    VocabWord('Rosso', 'Red', '🔴'),
    VocabWord('Blu', 'Blue', '🔵'),
    VocabWord('Verde', 'Green', '🟢'),
    VocabWord('Giallo', 'Yellow', '🟡'),
    VocabWord('Arancione', 'Orange', '🟠'),
    VocabWord('Viola', 'Purple', '🟣'),
    VocabWord('Rosa', 'Pink', '🌸'),
    VocabWord('Marrone', 'Brown', '🟤'),
    VocabWord('Nero', 'Black', '⚫'),
    VocabWord('Bianco', 'White', '⚪'),
    VocabWord('Grigio', 'Gray'),
    VocabWord('Oro', 'Gold'),

    // --- Family & people ---
    VocabWord('Famiglia', 'Family', '👨‍👩‍👧‍👦'),
    VocabWord('Mamma', 'Mom', '👩'),
    VocabWord('Papà', 'Dad', '👨'),
    VocabWord('Madre', 'Mother'),
    VocabWord('Padre', 'Father'),
    VocabWord('Fratello', 'Brother', '👦'),
    VocabWord('Sorella', 'Sister', '👧'),
    VocabWord('Nonno', 'Grandpa', '👴'),
    VocabWord('Nonna', 'Grandma', '👵'),
    VocabWord('Zio', 'Uncle'),
    VocabWord('Zia', 'Aunt'),
    VocabWord('Cugino', 'Cousin'),
    VocabWord('Figlio', 'Son'),
    VocabWord('Figlia', 'Daughter'),
    VocabWord('Bambino', 'Child', '👶'),
    VocabWord('Ragazzo', 'Boy', '👦'),
    VocabWord('Ragazza', 'Girl', '👧'),
    VocabWord('Uomo', 'Man', '👨'),
    VocabWord('Donna', 'Woman', '👩'),
    VocabWord('Amico', 'Friend', '🤝'),

    // --- Animals ---
    VocabWord('Cane', 'Dog', '🐕'),
    VocabWord('Gatto', 'Cat', '🐱'),
    VocabWord('Cavallo', 'Horse', '🐴'),
    VocabWord('Mucca', 'Cow', '🐄'),
    VocabWord('Maiale', 'Pig', '🐷'),
    VocabWord('Pecora', 'Sheep', '🐑'),
    VocabWord('Capra', 'Goat', '🐐'),
    VocabWord('Gallina', 'Hen', '🐔'),
    VocabWord('Gallo', 'Rooster', '🐓'),
    VocabWord('Anatra', 'Duck', '🦆'),
    VocabWord('Coniglio', 'Rabbit', '🐰'),
    VocabWord('Topo', 'Mouse', '🐭'),
    VocabWord('Uccello', 'Bird', '🐦'),
    VocabWord('Pesce', 'Fish', '🐟'),
    VocabWord('Squalo', 'Shark', '🦈'),
    VocabWord('Balena', 'Whale', '🐋'),
    VocabWord('Delfino', 'Dolphin', '🐬'),
    VocabWord('Polpo', 'Octopus', '🐙'),
    VocabWord('Leone', 'Lion', '🦁'),
    VocabWord('Tigre', 'Tiger', '🐯'),
    VocabWord('Orso', 'Bear', '🐻'),
    VocabWord('Lupo', 'Wolf', '🐺'),
    VocabWord('Volpe', 'Fox', '🦊'),
    VocabWord('Scimmia', 'Monkey', '🐵'),
    VocabWord('Elefante', 'Elephant', '🐘'),
    VocabWord('Giraffa', 'Giraffe', '🦒'),
    VocabWord('Zebra', 'Zebra', '🦓'),
    VocabWord('Serpente', 'Snake', '🐍'),
    VocabWord('Coccodrillo', 'Crocodile', '🐊'),
    VocabWord('Rana', 'Frog', '🐸'),
    VocabWord('Tartaruga', 'Turtle', '🐢'),
    VocabWord('Lumaca', 'Snail', '🐌'),
    VocabWord('Farfalla', 'Butterfly', '🦋'),
    VocabWord('Ape', 'Bee', '🐝'),
    VocabWord('Ragno', 'Spider', '🕷️'),
    VocabWord('Formica', 'Ant', '🐜'),
    VocabWord('Gufo', 'Owl', '🦉'),
    VocabWord('Pinguino', 'Penguin', '🐧'),
    VocabWord('Panda', 'Panda', '🐼'),
    VocabWord('Riccio', 'Hedgehog', '🦔'),

    // --- Food & drink ---
    VocabWord('Cibo', 'Food', '🍽️'),
    VocabWord('Pane', 'Bread', '🍞'),
    VocabWord('Pasta', 'Pasta', '🍝'),
    VocabWord('Pizza', 'Pizza', '🍕'),
    VocabWord('Riso', 'Rice', '🍚'),
    VocabWord('Formaggio', 'Cheese', '🧀'),
    VocabWord('Uovo', 'Egg', '🥚'),
    VocabWord('Carne', 'Meat', '🍖'),
    VocabWord('Pollo', 'Chicken', '🍗'),
    VocabWord('Prosciutto', 'Ham', '🍖'),
    VocabWord('Burro', 'Butter', '🧈'),
    VocabWord('Latte', 'Milk', '🥛'),
    VocabWord('Gelato', 'Ice cream', '🍨'),
    VocabWord('Torta', 'Cake', '🍰'),
    VocabWord('Biscotto', 'Cookie', '🍪'),
    VocabWord('Cioccolato', 'Chocolate', '🍫'),
    VocabWord('Caramella', 'Candy', '🍬'),
    VocabWord('Zucchero', 'Sugar'),
    VocabWord('Sale', 'Salt', '🧂'),
    VocabWord('Miele', 'Honey', '🍯'),
    VocabWord('Frutta', 'Fruit', '🍎'),
    VocabWord('Mela', 'Apple', '🍎'),
    VocabWord('Banana', 'Banana', '🍌'),
    VocabWord('Arancia', 'Orange (fruit)', '🍊'),
    VocabWord('Limone', 'Lemon', '🍋'),
    VocabWord('Fragola', 'Strawberry', '🍓'),
    VocabWord('Uva', 'Grapes', '🍇'),
    VocabWord('Pesca', 'Peach', '🍑'),
    VocabWord('Ciliegia', 'Cherry', '🍒'),
    VocabWord('Anguria', 'Watermelon', '🍉'),
    VocabWord('Ananas', 'Pineapple', '🍍'),
    VocabWord('Verdura', 'Vegetable', '🥗'),
    VocabWord('Pomodoro', 'Tomato', '🍅'),
    VocabWord('Patata', 'Potato', '🥔'),
    VocabWord('Carota', 'Carrot', '🥕'),
    VocabWord('Cipolla', 'Onion', '🧅'),
    VocabWord('Aglio', 'Garlic', '🧄'),
    VocabWord('Insalata', 'Salad', '🥗'),
    VocabWord('Mais', 'Corn', '🌽'),
    VocabWord('Fungo', 'Mushroom', '🍄'),
    VocabWord('Acqua', 'Water', '💧'),
    VocabWord('Succo', 'Juice', '🧃'),
    VocabWord('Caffè', 'Coffee', '☕'),
    VocabWord('Tè', 'Tea', '🍵'),
    VocabWord('Panino', 'Sandwich', '🥪'),
    VocabWord('Zuppa', 'Soup', '🍲'),
    VocabWord('Colazione', 'Breakfast', '🍳'),
    VocabWord('Pranzo', 'Lunch'),
    VocabWord('Cena', 'Dinner', '🍽️'),

    // --- Body ---
    VocabWord('Corpo', 'Body'),
    VocabWord('Testa', 'Head'),
    VocabWord('Capelli', 'Hair'),
    VocabWord('Occhi', 'Eyes', '👀'),
    VocabWord('Naso', 'Nose', '👃'),
    VocabWord('Bocca', 'Mouth', '👄'),
    VocabWord('Dente', 'Tooth', '🦷'),
    VocabWord('Orecchio', 'Ear', '👂'),
    VocabWord('Faccia', 'Face'),
    VocabWord('Braccio', 'Arm', '💪'),
    VocabWord('Mano', 'Hand', '✋'),
    VocabWord('Dito', 'Finger'),
    VocabWord('Gamba', 'Leg', '🦵'),
    VocabWord('Piede', 'Foot', '🦶'),
    VocabWord('Pancia', 'Belly'),
    VocabWord('Cuore', 'Heart', '❤️'),

    // --- Clothing ---
    VocabWord('Vestiti', 'Clothes', '👕'),
    VocabWord('Maglietta', 'T-shirt', '👕'),
    VocabWord('Camicia', 'Shirt', '👔'),
    VocabWord('Pantaloni', 'Pants', '👖'),
    VocabWord('Gonna', 'Skirt'),
    VocabWord('Vestito', 'Dress', '👗'),
    VocabWord('Maglione', 'Sweater', '🧥'),
    VocabWord('Giacca', 'Jacket', '🧥'),
    VocabWord('Cappotto', 'Coat', '🧥'),
    VocabWord('Scarpe', 'Shoes', '👟'),
    VocabWord('Stivali', 'Boots', '👢'),
    VocabWord('Calzini', 'Socks', '🧦'),
    VocabWord('Cappello', 'Hat', '🧢'),
    VocabWord('Guanti', 'Gloves', '🧤'),
    VocabWord('Sciarpa', 'Scarf', '🧣'),
    VocabWord('Occhiali', 'Glasses', '👓'),
    VocabWord('Orologio', 'Watch / Clock', '⌚'),
    VocabWord('Borsa', 'Bag', '👜'),
    VocabWord('Zaino', 'Backpack', '🎒'),

    // --- House & objects ---
    VocabWord('Casa', 'House', '🏠'),
    VocabWord('Porta', 'Door', '🚪'),
    VocabWord('Finestra', 'Window', '🪟'),
    VocabWord('Camera', 'Bedroom', '🛏️'),
    VocabWord('Cucina', 'Kitchen', '🍳'),
    VocabWord('Bagno', 'Bathroom', '🚿'),
    VocabWord('Giardino', 'Garden', '🌷'),
    VocabWord('Letto', 'Bed', '🛏️'),
    VocabWord('Sedia', 'Chair', '🪑'),
    VocabWord('Tavolo', 'Table'),
    VocabWord('Divano', 'Sofa', '🛋️'),
    VocabWord('Lampada', 'Lamp', '💡'),
    VocabWord('Specchio', 'Mirror', '🪞'),
    VocabWord('Chiave', 'Key', '🔑'),
    VocabWord('Telefono', 'Phone', '📱'),
    VocabWord('Computer', 'Computer', '💻'),
    VocabWord('Libro', 'Book', '📚'),
    VocabWord('Penna', 'Pen', '🖊️'),
    VocabWord('Matita', 'Pencil', '✏️'),
    VocabWord('Carta', 'Paper', '📄'),

    // --- School ---
    VocabWord('Scuola', 'School', '🏫'),
    VocabWord('Classe', 'Class'),
    VocabWord('Maestra', 'Teacher', '👩‍🏫'),
    VocabWord('Studente', 'Student', '🧑‍🎓'),
    VocabWord('Lezione', 'Lesson'),
    VocabWord('Compiti', 'Homework', '📝'),
    VocabWord('Esame', 'Exam'),
    VocabWord('Quaderno', 'Notebook', '📓'),
    VocabWord('Biblioteca', 'Library', '📚'),
    VocabWord('Palestra', 'Gym', '🏋️'),

    // --- Nature & weather ---
    VocabWord('Sole', 'Sun', '☀️'),
    VocabWord('Luna', 'Moon', '🌙'),
    VocabWord('Stella', 'Star', '⭐'),
    VocabWord('Cielo', 'Sky'),
    VocabWord('Nuvola', 'Cloud', '☁️'),
    VocabWord('Pioggia', 'Rain', '🌧️'),
    VocabWord('Neve', 'Snow', '❄️'),
    VocabWord('Vento', 'Wind', '💨'),
    VocabWord('Arcobaleno', 'Rainbow', '🌈'),
    VocabWord('Caldo', 'Hot', '🥵'),
    VocabWord('Freddo', 'Cold', '🥶'),
    VocabWord('Albero', 'Tree', '🌳'),
    VocabWord('Fiore', 'Flower', '🌸'),
    VocabWord('Foglia', 'Leaf', '🍃'),
    VocabWord('Erba', 'Grass', '🌱'),
    VocabWord('Montagna', 'Mountain', '⛰️'),
    VocabWord('Mare', 'Sea', '🌊'),
    VocabWord('Lago', 'Lake'),
    VocabWord('Fiume', 'River'),
    VocabWord('Spiaggia', 'Beach', '🏖️'),
    VocabWord('Isola', 'Island', '🏝️'),
    VocabWord('Bosco', 'Forest', '🌲'),
    VocabWord('Terra', 'Earth', '🌍'),
    VocabWord('Fuoco', 'Fire', '🔥'),

    // --- Time & calendar ---
    VocabWord('Tempo', 'Time / Weather', '⏰'),
    VocabWord('Giorno', 'Day'),
    VocabWord('Notte', 'Night', '🌙'),
    VocabWord('Mattina', 'Morning', '🌅'),
    VocabWord('Sera', 'Evening', '🌆'),
    VocabWord('Oggi', 'Today'),
    VocabWord('Domani', 'Tomorrow'),
    VocabWord('Ieri', 'Yesterday'),
    VocabWord('Adesso', 'Now'),
    VocabWord('Ora', 'Hour', '🕐'),
    VocabWord('Minuto', 'Minute'),
    VocabWord('Settimana', 'Week'),
    VocabWord('Mese', 'Month', '📅'),
    VocabWord('Anno', 'Year'),
    VocabWord('Lunedì', 'Monday'),
    VocabWord('Martedì', 'Tuesday'),
    VocabWord('Mercoledì', 'Wednesday'),
    VocabWord('Giovedì', 'Thursday'),
    VocabWord('Venerdì', 'Friday'),
    VocabWord('Sabato', 'Saturday'),
    VocabWord('Domenica', 'Sunday'),
    VocabWord('Primavera', 'Spring', '🌷'),
    VocabWord('Estate', 'Summer', '☀️'),
    VocabWord('Autunno', 'Autumn', '🍂'),
    VocabWord('Inverno', 'Winter', '❄️'),
    VocabWord('Compleanno', 'Birthday', '🎂'),

    // --- Places & travel ---
    VocabWord('Città', 'City', '🏙️'),
    VocabWord('Paese', 'Town / Country'),
    VocabWord('Strada', 'Street'),
    VocabWord('Piazza', 'Square', '🏛️'),
    VocabWord('Negozio', 'Shop', '🏪'),
    VocabWord('Mercato', 'Market'),
    VocabWord('Ristorante', 'Restaurant', '🍽️'),
    VocabWord('Ospedale', 'Hospital', '🏥'),
    VocabWord('Farmacia', 'Pharmacy', '💊'),
    VocabWord('Banca', 'Bank', '🏦'),
    VocabWord('Chiesa', 'Church', '⛪'),
    VocabWord('Museo', 'Museum', '🏛️'),
    VocabWord('Parco', 'Park', '🌳'),
    VocabWord('Stazione', 'Station', '🚉'),
    VocabWord('Aeroporto', 'Airport', '✈️'),
    VocabWord('Treno', 'Train', '🚂'),
    VocabWord('Autobus', 'Bus', '🚌'),
    VocabWord('Macchina', 'Car', '🚗'),
    VocabWord('Bicicletta', 'Bicycle', '🚲'),
    VocabWord('Barca', 'Boat', '⛵'),
    VocabWord('Aereo', 'Plane', '✈️'),
    VocabWord('Nave', 'Ship', '🚢'),
    VocabWord('Biglietto', 'Ticket', '🎫'),
    VocabWord('Valigia', 'Suitcase', '🧳'),
    VocabWord('Albergo', 'Hotel', '🏨'),
    VocabWord('Ponte', 'Bridge', '🌉'),

    // --- Verbs ---
    VocabWord('Essere', 'To be'),
    VocabWord('Avere', 'To have'),
    VocabWord('Fare', 'To do / make'),
    VocabWord('Andare', 'To go'),
    VocabWord('Venire', 'To come'),
    VocabWord('Dire', 'To say'),
    VocabWord('Vedere', 'To see', '👀'),
    VocabWord('Sentire', 'To hear / feel'),
    VocabWord('Parlare', 'To speak', '🗣️'),
    VocabWord('Mangiare', 'To eat', '🍽️'),
    VocabWord('Bere', 'To drink', '🥤'),
    VocabWord('Dormire', 'To sleep', '😴'),
    VocabWord('Correre', 'To run', '🏃'),
    VocabWord('Camminare', 'To walk', '🚶'),
    VocabWord('Saltare', 'To jump'),
    VocabWord('Giocare', 'To play', '🎮'),
    VocabWord('Leggere', 'To read', '📖'),
    VocabWord('Scrivere', 'To write', '✍️'),
    VocabWord('Ascoltare', 'To listen', '🎧'),
    VocabWord('Guardare', 'To watch'),
    VocabWord('Comprare', 'To buy', '🛒'),
    VocabWord('Pagare', 'To pay', '💰'),
    VocabWord('Aprire', 'To open'),
    VocabWord('Chiudere', 'To close'),
    VocabWord('Prendere', 'To take'),
    VocabWord('Dare', 'To give'),
    VocabWord('Portare', 'To bring'),
    VocabWord('Mettere', 'To put'),
    VocabWord('Trovare', 'To find'),
    VocabWord('Cercare', 'To look for', '🔍'),
    VocabWord('Vincere', 'To win', '🏆'),
    VocabWord('Imparare', 'To learn', '📚'),
    VocabWord('Capire', 'To understand', '💡'),
    VocabWord('Sapere', 'To know'),
    VocabWord('Pensare', 'To think', '🤔'),
    VocabWord('Volere', 'To want'),
    VocabWord('Potere', 'To be able to'),
    VocabWord('Dovere', 'To have to'),
    VocabWord('Amare', 'To love', '❤️'),
    VocabWord('Ridere', 'To laugh', '😂'),
    VocabWord('Piangere', 'To cry', '😢'),
    VocabWord('Cantare', 'To sing', '🎤'),
    VocabWord('Ballare', 'To dance', '💃'),
    VocabWord('Disegnare', 'To draw', '🎨'),
    VocabWord('Cucinare', 'To cook', '🍳'),
    VocabWord('Aiutare', 'To help', '🤝'),
    VocabWord('Chiamare', 'To call', '📞'),
    VocabWord('Aspettare', 'To wait'),
    VocabWord('Lavorare', 'To work'),
    VocabWord('Studiare', 'To study'),
    VocabWord('Viaggiare', 'To travel', '✈️'),
    VocabWord('Nuotare', 'To swim', '🏊'),
    VocabWord('Ricordare', 'To remember'),

    // --- Adjectives ---
    VocabWord('Grande', 'Big'),
    VocabWord('Piccolo', 'Small'),
    VocabWord('Alto', 'Tall'),
    VocabWord('Basso', 'Short (height)'),
    VocabWord('Lungo', 'Long'),
    VocabWord('Nuovo', 'New'),
    VocabWord('Vecchio', 'Old'),
    VocabWord('Giovane', 'Young'),
    VocabWord('Buono', 'Good'),
    VocabWord('Cattivo', 'Bad'),
    VocabWord('Bello', 'Beautiful', '😍'),
    VocabWord('Brutto', 'Ugly'),
    VocabWord('Facile', 'Easy'),
    VocabWord('Difficile', 'Difficult'),
    VocabWord('Veloce', 'Fast'),
    VocabWord('Lento', 'Slow', '🐌'),
    VocabWord('Forte', 'Strong', '💪'),
    VocabWord('Debole', 'Weak'),
    VocabWord('Pieno', 'Full'),
    VocabWord('Vuoto', 'Empty'),
    VocabWord('Pulito', 'Clean'),
    VocabWord('Sporco', 'Dirty'),
    VocabWord('Felice', 'Happy', '😊'),
    VocabWord('Triste', 'Sad', '😢'),
    VocabWord('Stanco', 'Tired', '😴'),
    VocabWord('Arrabbiato', 'Angry', '😠'),
    VocabWord('Gentile', 'Kind'),
    VocabWord('Simpatico', 'Nice / Funny'),
    VocabWord('Ricco', 'Rich', '💰'),
    VocabWord('Povero', 'Poor'),
    VocabWord('Primo', 'First'),
    VocabWord('Ultimo', 'Last'),
    VocabWord('Importante', 'Important'),

    // --- Question words & connectors ---
    VocabWord('Chi', 'Who'),
    VocabWord('Cosa', 'What'),
    VocabWord('Dove', 'Where', '📍'),
    VocabWord('Quando', 'When', '⏰'),
    VocabWord('Perché', 'Why / Because'),
    VocabWord('Come', 'How'),
    VocabWord('Quanto', 'How much'),
    VocabWord('Quale', 'Which'),
    VocabWord('Molto', 'Very / A lot'),
    VocabWord('Poco', 'A little'),
    VocabWord('Troppo', 'Too much'),
    VocabWord('Anche', 'Also'),
    VocabWord('Sempre', 'Always'),
    VocabWord('Mai', 'Never'),
    VocabWord('Qui', 'Here'),
    VocabWord('Là', 'There'),
    VocabWord('Con', 'With'),
    VocabWord('Senza', 'Without'),
    VocabWord('Prima', 'Before'),
    VocabWord('Dopo', 'After'),
    VocabWord('Vicino', 'Near'),
    VocabWord('Lontano', 'Far'),
    VocabWord('Sopra', 'Above'),
    VocabWord('Sotto', 'Under'),
  ];

  /// All words that carry an emoji (for the Emoji Match game).
  static List<VocabWord> get withEmoji =>
      all.where((VocabWord w) => w.hasEmoji).toList();
}
